baseURL = "https://mq1.eu/"
languageCode = "en-us"
title = "Manuel Quarneti"

[markup.goldmark.renderer]
unsafe = true

[params]
email = "manuelquarneti@gmail.com"
githubProfile = "https://github.com/mq1"
linkedinProfile = "https://www.linkedin.com/in/mq1"
telegramProfile = "https://t.me/quarno"
