[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "14"

[build]
  publish = "dist"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[[redirects]]
  from = "/top-for-spotify/*"
  to = "https://top-for-spotify.netlify.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/cv.pdf"
  to = "https://mq1.github.io/mq1/cv.pdf"
  status = 200
  force = true

[[redirects]]
  from = "/aboutMe"
  to = "https://mq1.github.io/mq1/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/ali"
  to = "https://raw.githubusercontent.com/mq1/ali/master/ali"
  status = 200
  force = true